=== adrish00/techmentro_labworks/WS_TM_3.0_XMLParsersWithDTD/src/books.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY r1 "It is recomended for basic users">
<!ENTITY r2 "It is recomended for advanced users">
<!ELEMENT books (book)*>
<!ELEMENT book (name,writer,rating)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT rating (#PCDATA)>

=== adrish00/techmentro_labworks/WS_TM_3.0_XMLParsersWithDTD/bin/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "src/books.dtd" >
<books>
<book>
<name>Spring &amp; Hibernate</name>
<writer>S. Satish</writer>
<rating>&r1;</rating>
</book>
<book>
<name>&quot;Struts 2 &quot;</name>
<writer>Raman Singh</writer>
<rating>&r2;</rating>
</book>
</books>
